# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(686, 585)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setDocumentMode(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout_2.addWidget(self.graphicsView)
        self.obtion_groupbox = QtWidgets.QGroupBox(self.centralwidget)
        self.obtion_groupbox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.obtion_groupbox.sizePolicy().hasHeightForWidth())
        self.obtion_groupbox.setSizePolicy(sizePolicy)
        self.obtion_groupbox.setMinimumSize(QtCore.QSize(10, 0))
        self.obtion_groupbox.setMaximumSize(QtCore.QSize(1677, 16777215))
        self.obtion_groupbox.setBaseSize(QtCore.QSize(30, 0))
        self.obtion_groupbox.setAutoFillBackground(False)
        self.obtion_groupbox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.obtion_groupbox.setFlat(True)
        self.obtion_groupbox.setCheckable(False)
        self.obtion_groupbox.setObjectName("obtion_groupbox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.obtion_groupbox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 171, 361))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.option_tools_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.option_tools_layout.setContentsMargins(0, 0, 0, 0)
        self.option_tools_layout.setObjectName("option_tools_layout")
        self.btn_pred_folder = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_pred_folder.sizePolicy().hasHeightForWidth())
        self.btn_pred_folder.setSizePolicy(sizePolicy)
        self.btn_pred_folder.setObjectName("btn_pred_folder")
        self.option_tools_layout.addWidget(self.btn_pred_folder)
        self.lbl_pred_folder = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_pred_folder.sizePolicy().hasHeightForWidth())
        self.lbl_pred_folder.setSizePolicy(sizePolicy)
        self.lbl_pred_folder.setText("")
        self.lbl_pred_folder.setWordWrap(True)
        self.lbl_pred_folder.setObjectName("lbl_pred_folder")
        self.option_tools_layout.addWidget(self.lbl_pred_folder)
        self.btn_img_folder = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_img_folder.sizePolicy().hasHeightForWidth())
        self.btn_img_folder.setSizePolicy(sizePolicy)
        self.btn_img_folder.setObjectName("btn_img_folder")
        self.option_tools_layout.addWidget(self.btn_img_folder)
        self.lbl_img_folder = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_img_folder.sizePolicy().hasHeightForWidth())
        self.lbl_img_folder.setSizePolicy(sizePolicy)
        self.lbl_img_folder.setText("")
        self.lbl_img_folder.setWordWrap(True)
        self.lbl_img_folder.setObjectName("lbl_img_folder")
        self.option_tools_layout.addWidget(self.lbl_img_folder)
        self.btn_xml_folder = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_xml_folder.sizePolicy().hasHeightForWidth())
        self.btn_xml_folder.setSizePolicy(sizePolicy)
        self.btn_xml_folder.setObjectName("btn_xml_folder")
        self.option_tools_layout.addWidget(self.btn_xml_folder)
        self.lbl_xml_folder = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_xml_folder.sizePolicy().hasHeightForWidth())
        self.lbl_xml_folder.setSizePolicy(sizePolicy)
        self.lbl_xml_folder.setText("")
        self.lbl_xml_folder.setWordWrap(True)
        self.lbl_xml_folder.setObjectName("lbl_xml_folder")
        self.option_tools_layout.addWidget(self.lbl_xml_folder)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_pre = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_pre.setObjectName("btn_pre")
        self.horizontalLayout_3.addWidget(self.btn_pre)
        self.btn_next = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_next.setObjectName("btn_next")
        self.horizontalLayout_3.addWidget(self.btn_next)
        self.option_tools_layout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cbx_gt_box = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.cbx_gt_box.setObjectName("cbx_gt_box")
        self.verticalLayout_2.addWidget(self.cbx_gt_box)
        self.cbx_pred_box = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.cbx_pred_box.setObjectName("cbx_pred_box")
        self.verticalLayout_2.addWidget(self.cbx_pred_box)
        self.option_tools_layout.addLayout(self.verticalLayout_2)
        self.option_tools_layout.setStretch(0, 2)
        self.option_tools_layout.setStretch(1, 2)
        self.option_tools_layout.setStretch(2, 2)
        self.option_tools_layout.setStretch(3, 2)
        self.option_tools_layout.setStretch(4, 2)
        self.option_tools_layout.setStretch(5, 2)
        self.option_tools_layout.setStretch(6, 2)
        self.option_tools_layout.setStretch(7, 3)
        self.info_label = QtWidgets.QLabel(self.obtion_groupbox)
        self.info_label.setGeometry(QtCore.QRect(10, 410, 161, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_label.sizePolicy().hasHeightForWidth())
        self.info_label.setSizePolicy(sizePolicy)
        self.info_label.setText("")
        self.info_label.setWordWrap(True)
        self.info_label.setObjectName("info_label")
        self.horizontalLayout_2.addWidget(self.obtion_groupbox)
        self.horizontalLayout_2.setStretch(0, 5)
        self.horizontalLayout_2.setStretch(1, 2)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 686, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.btn_xml_folder, self.graphicsView)
        MainWindow.setTabOrder(self.graphicsView, self.btn_img_folder)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.obtion_groupbox.setTitle(_translate("MainWindow", "Options"))
        self.btn_pred_folder.setText(_translate("MainWindow", "Prediction Folder"))
        self.btn_img_folder.setText(_translate("MainWindow", "Images Folder"))
        self.btn_xml_folder.setText(_translate("MainWindow", "xml Folder"))
        self.btn_pre.setText(_translate("MainWindow", "pre"))
        self.btn_next.setText(_translate("MainWindow", "next"))
        self.cbx_gt_box.setText(_translate("MainWindow", "show gt boxes"))
        self.cbx_pred_box.setText(_translate("MainWindow", "show pred boxes"))

